#!/usr/bin/env bash
# Transfers a file from our a client to a server.
if [ -v $0 ] | [ -v $1 ] | [ -v $2 ] | [ -v $3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp $4 $0 $3@$2:$1
fi
