#!/usr/bin/env bash
# This script prints "Best School" 10 times using a while loop.
# It also print "Hi" on the 9th iteration.
i=0
while [ $i -ne 10 ]
do
    echo "Best School"
    if [ $i -eq 8 ]
    then
	echo "Hi"
    fi
    i=$((i+1))
done
