#!/usr/bin/env bash
# This script loops 10 times, printing "Best School", except for the 4th
# 8th iteration, where it prints "bad luck" and "good luck" respectively.
i=0
while [ $i -ne 10 ]
do
    if [ $i -eq 3 ]
    then
	echo "bad luck"
    elif [ $i -eq 7 ]
    then
	echo "good luck"
    else
	echo "Best School"
    fi
    i=$((i+1))
done
