#!/usr/bin/env bash
# This script loops 20 times, printing 1 through 20, additional information
# is printed based on case.
i=1
while [ $i -le 20 ]
do
    echo $i
    case $i in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    ((i++))
done
