#!/usr/bin/env bash
# This script loops 20 times, printing 1 through 20, additional information
# is printed based on case.
i=1
while [ $i -ne 21 ]
do
    case $i in
	4)
	    echo "bad luck from China"
	    ;;
	8)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
	*)
	    echo $i
    esac
    i=$((i+1))
done
n
