#!/usr/bin/env bash
# This script prints information about a file.
if [ -e "$1" ]
then
    echo "$1" "file exists"
    if [ -s "$1" ]
    then
	echo "$1" "file is not empty"
    else
	echo "$1" "file is empty"
    fi

    if [ -f "$1" ]
    then
	echo "$1" "file is a regular file"
    fi
else
    echo "$1" "file does not exist"
fi
